name: just_ready
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1e

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  injectable: ^2.3.2
  get_it: ^7.6.6
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  provider: ^6.1.1
  intl: ^0.18.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: 2.0.5

  firebase_auth: ^4.16.0
  reactive_forms: ^16.1.1
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  flutter_hooks: ^0.20.4
  hooked_bloc: ^1.4.3

  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  logger: ^2.0.2+1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.6
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.4.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/illustrations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Black.ttf
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
